# Generated by Django 2.0 on 2017-12-15 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='title',
        ),
        migrations.AddField(
            model_name='post',
            name='user',
            field=models.CharField(default='lora', max_length=30),
            preserve_default=False,
        ),
    ]
